cc_binary(
  name = "test_abs",
  srcs = ["test_abs.cc"],
)

cc_binary(
  name = "test_advance",
  srcs = ["test_advance.cc"],
)

cc_binary(
  name = "test_auto",
  srcs = ["test_auto.cc"],
)

cc_binary(
  name = "test_construct",
  srcs = ["test_construct.cc"],
)

